### ISSUE TITLE
How to run on DD dataset？

### ISSUE THREAD

**Issue by FENGA1** [cszhangzhen/HGP-SL#1]
Hi, thanks for your code. But when I run python main.py --dataset DD, there is an error as follows:

RuntimeError: CUDA out of memory. Tried to allocate 18.75 GiB (GPU 0; 15.90 GiB total capacity; 2.36 GiB already allocated; 10.80 GiB free; 559.64 MiB cached)

**Comment by cszhangzhen** [comment]
Hi,

DD dataset has relatively larger average nodes per graph. You can reduce the batch_size = 64 or 32, which depends on your GPU memory.

**Comment by FENGA1** [comment]
Thanks for your reply, I reduced the batch_size to 32 and the accuracy was 0.731092

**Comment by cszhangzhen** [comment]
Hi, you need to tune the hyper-parameters.

**Comment by cszhangzhen** [comment]
Hi, I have updated parameter settings at README.MD
