### ISSUE TITLE
Segmentation error

### ISSUE THREAD

**Issue by zaixizhang** [cszhangzhen/HGP-SL#2]
Hi, I run the code with"python main.py", but it outputs"segmentation error". How can I fix it?

**Comment by cszhangzhen** [comment]
Hi, 

Thanks for your feedback.

The codes run successfully with pyCharm IDE. However, it indeed occurs segmentation error with command line. 

I use gdb to debug the code and find that the error is related the **sip package**. See information below:

(gdb) file python
Reading symbols from python...done.
(gdb) run main.py 
Starting program: /.conda/envs/py36/bin/python main.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
PyType_IsSubtype (a=0x626f6174656d5f74, b=0x1554efed8660)
    at /tmp/build/80754af9/python_1540319457073/work/Objects/typeobject.c:1357
1357	/tmp/build/80754af9/python_1540319457073/work/Objects/typeobject.c: No such file or directory.
(gdb) bt
PyType_IsSubtype (a=0x626f6174656d5f74, b=0x1554efed8660)
    at /tmp/build/80754af9/python_1540319457073/work/Objects/typeobject.c:1357
0x00001554efcce0cf in ?? () from /.conda/envs/py36/lib/python3.6/site-packages/sip.so
0x00001554efcce935 in ?? () from /.conda/envs/py36/lib/python3.6/site-packages/sip.so

**Solution** :
**update your sip package with the following command:**
conda install -c conda-forge sip=4.18.1

After updating your sip package, the codes can successfully run with both pyCharm IDE and command line.

**Comment by zaixizhang** [comment]
Thanks, I have fixed the segementation error by updating pytorch and reinstalling pyG packages.
However, I got another problem. When I run"python main.py", another error occured at the 31th line of layers.py.  It said coalesce got one unexpected keyword argument "fill_value". Can I just delete this arguement?

**Comment by cszhangzhen** [comment]
Hi,

This is caused by the updating of torch-sparse.

I have updated the code in layers.py. Please download the code and run again.

**Comment by zaixizhang** [comment]
Thanks for your reply! I can run the code successfully now.
