### ISSUE TITLE
How to draw a graph as beautiful as model.png

### ISSUE THREAD

**Issue by bobolike123** [cszhangzhen/HGP-SL#4]
I have given a star on this code for its high quality. Strangely,it has only stars less than 100. Maybe it is lack of propaganda. I am a researcher focus on intrusion detection, and GNN may provide a novel idea on anomalous network traffic analysis. Noting that the graph "model.png" is such beautiful,could you tell me how you draw this graph? Visio? PPT? or other powerful tools? And could you share the source file of the graph?

**Comment by cszhangzhen** [comment]
Hi, Thank you.

The model framework is drawn via Visio. Why do you need the source graph file?

**Comment by bobolike123** [comment]
Thanks for your replying. I just want it for reference to improve my drawing ability,and no sharing will also be ok. Imitation and practice could also be the way.The issue will be closed and I am looking forward your next excellent paper.
